### ISSUE TITLE
hello how make income call  reject or accept video call 

### ISSUE THREAD

**Issue by eslam2010011** [AgoraIO-Community/Android-UIKit#1]
hello how make income call  reject or accept video call

**Comment by samyak-jain** [comment]
To have incoming call accept and reject functionality, you can use refer this repository: https://github.com/AgoraIO/Advanced-Video/tree/dev/backup/Calling-Interface/Agora-RTC-With-ConnectionService-Android

After you implemented connectionservice, you can easily start the uikit activity when the user accepts the call.
