### ISSUE TITLE
Web to Android  video call issue

### ISSUE THREAD

**Issue by akashydv04** [AgoraIO-Community/Android-UIKit#18]
**When i was testing by initiating video call from web and join from android device .
User join channel successfully but on user joined method not calling** 

If we try web to web video call everything working fine and when we test android to android it working fine .

When call initiate from android then web can join and working well .

please resolve my issue as soon as possible 
Thank you

**Comment by maxxfrazer** [comment]
Hi @akashydv04, could you give a little information about your environment and confirm that you're using the UIKit for your project?

There is an issue template in this repo, so please add in all the details from that if you can
