### ISSUE TITLE
Screen Share while video calling

### ISSUE THREAD

**Issue by thegitparticle** [AgoraIO-Community/Android-UIKit#20]
**Is your feature request related to a problem? Please describe.**
Screen sharing while video calling. 

**Describe the solution you'd like**
An options to share screen while talking with people. Here is the agora docs implementation of it - https://docs.agora.io/en/Video/screensharing_android?platform=Android

**Comment by Meherdeep** [comment]
@thegitparticle Screen sharing is in our roadmap and will soon be added to the UIKit in the coming releases.

**Comment by thegitparticle** [comment]
@Meherdeep meanwhile, are there any kotlin based implementations I can refer to for screen sharing?

**Comment by Meherdeep** [comment]
@thegitparticle Sorry there are no official Kotlin based screen sharing examples available as of now. But there is a java screen sharing guide that you can refer: https://docs.agora.io/en/Video/screensharing_android?platform=Android

**Comment by vishalkumarsinghvi** [comment]
@Meherdeep  Any repo or working example is there on Github or medium.

**Comment by maxxfrazer** [comment]
@vishalkumarsinghvi this repo has a screen sharing example for android
https://github.com/AgoraIO/API-Examples

**Comment by vishalkumarsinghvi** [comment]
Hey @maxxfrazer ,
Thank you for replying but the documentation and example was very complecated to understand.
