### ISSUE TITLE
Duplicate class found error occured on building v4.0.0

### ISSUE THREAD

**Issue by gopalawasthi123** [AgoraIO-Community/Android-UIKit#27]
**Describe the bug**
On integrating the Agora VideoUIKit-Android gives duplicate class error on compiling

**To Reproduce**
1. Go to build.gradle and add  implementation "com.github.AgoraIO-Community:Android-UIKit:v4.0.0"
2. Click on make project
3. Scroll down to build console
4. See error `Duplicate class io.agora.agorauikit_android.AgoraButton found in modules final-debug-v4.0.0-runtime (com.github.AgoraIO-Community.Android-UIKit:final-debug:v4.0.0) and final-v4.0.0-runtime (com.github.AgoraIO-Community.Android-UIKit:final:v4.0.0)`

**Expected behavior**
Project should be build

**Screenshots**
**Smartphone (please complete the following information):**
 - <img width="1337" alt="image" src="https://user-images.githubusercontent.com/32213215/193789182-29955015-a2e6-4f39-907a-d1026f13d612.png">
- target SDK - 33

**Comment by Meherdeep** [comment]
@gopalawasthi123  can you try using this as a dependency for the latest 4.0.0 version
```implementation 'com.github.AgoraIO-Community.VideoUIKit-Android:final:v4.0.0'```
