### ISSUE TITLE
[BUG] Black screen when connecting or rotating the device

### ISSUE THREAD

**Issue by A-Cordero** [AgoraIO-Community/Android-UIKit#32]
After doing all the configuration of AgoraIO-Community:Android-UIKit-version 2.0.1 , the only version that does not conflict with
agora-rtc, everything works correctly in floating mode, but the remote screen sometimes goes black, this also happens if I rotate the phone repeatedly the screen goes black, although the audio output works

**Comment by maxxfrazer** [comment]
Hi @A-Cordero, I just noticed that some of the URLs in the README were outdated, please try with the following dependency:

```
dependencies {
  implementation 'com.github.AgoraIO-Community:VideoUIKit-Android:v4.0.1'
}
```

**Comment by maxxfrazer** [comment]
There's also a bug reporting template in this repo, please fill out the information and put it all in this issue.

**Comment by A-Cordero** [comment]
Sorry for not use template, when i use VideoUIKit-Android:v4.0.1 the version told me reports in a new project that there are duplicate classes 
![image](https://user-images.githubusercontent.com/37815669/206481524-b70249ef-0b15-48b3-a424-a562f981d19a.png)

**Comment by marutifh** [comment]
Hi @A-Cordero, 

Did you find any solution to this?

EDIT:: 

Issue got resolved with this:

`
dependencies {
	        implementation 'com.github.AgoraIO-Community.VideoUIKit-Android:final:v4.0.1'
}
	`
