### ISSUE TITLE
App size increased by  ~190MB

### ISSUE THREAD

**Issue by marutifh** [AgoraIO-Community/Android-UIKit#34]
Hi all, 

I used the Android UI Kit for implementation and observed that my application size grew massively. 

In my application I am using Agora for just Video call between two people, no customisation. Any possible solutions to reduce the application size? 

Thank you.

**Comment by maxxfrazer** [comment]
Hi @marutifh, the core SDK has reduced a lot in size in the latest version, we just need to update the UI Kit to use that version and you should see an improvement. @Meherdeep please look into getting the UI Kit up to date.

**Comment by maxxfrazer** [comment]
UI Kit has been updated for this
